<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4hqkro1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4hqkro1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4hqkro1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4hqkro1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4hqkro1\appDevDebugProjectContainer(array(
    'container.build_hash' => '4hqkro1',
    'container.build_id' => 'a04d51ec',
    'container.build_time' => 1548191124,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4hqkro1');
